// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJDxd9eUZdnbEY3zuTK_g5_zNdBzf2Yhw',
    appId: '1:581581306667:android:75c0c443293b8e2e83636e',
    messagingSenderId: '581581306667',
    projectId: 'nurse-assistant-system',
    databaseURL: 'https://nurse-assistant-system-default-rtdb.firebaseio.com',
    storageBucket: 'nurse-assistant-system.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPDO1ucIE-bhvq9m0KfKGp5ifIJ5wi4vY',
    appId: '1:581581306667:ios:01e1d394d511343183636e',
    messagingSenderId: '581581306667',
    projectId: 'nurse-assistant-system',
    databaseURL: 'https://nurse-assistant-system-default-rtdb.firebaseio.com',
    storageBucket: 'nurse-assistant-system.appspot.com',
    iosBundleId: 'com.enurse_systemsystem.enurse_systemSystem',
  );

}